# Generated by Django 4.2.6 on 2023-10-05 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["status", "-created"]},
        ),
    ]
